### PR TITLE
Add constants and cleanup

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by oppiliappan** [comment]
sweet! syntax highlighting is a bit broken, but we can make do! this makes it easier to add variable support i think.

thank you for your contribution!

**Comment by pickfire** [comment]
I think the syntax highlighting was already broken from previous commit, especially the ` = ans` part.

**Comment by pickfire** [comment]
I think the syntax highlighting was already broken from previous commit, especially the ` = ans` part.

**Comment by oppiliappan** [comment]
yep you are right. ill add some commits to this pr, fix them and merge them to master.

thank you!

**Comment by pickfire** [comment]
I am wondering if the syntax highlighting at the back could be tested, so far I am not sure how.

**Comment by oppiliappan** [comment]
```rust
// To debug rustyline:
// RUST_LOG=rustyline=debug cargo run --example example 2> debug.log
```

i picked this up from the example code over at the rustyline repo. it might come in handy! i am a little tied up now, but ill give it a go sometime this week.

seems to require the `env_logger` crate.

**Comment by oppiliappan** [comment]
hey @pickfire, i pulled your fork and made some changes locally and merged it to master. (some improvements to highlighting)

sorry i messed up this pr, consider it merged. its your code that runs master!

**Pull request merged**
